<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>

  <body>
    <script>
      function pro() {
        return new Promise(function (resolve, reject) {
          reject(1);
        });
      }
      async function test() {
        try {
          await pro();
        } catch (error) {
          console.log(error);
        }
      }
      test();

      //   不采用下面的方法在函数外面捕获错误, 如何在函数内部捕获错误?
      //   test().catch((err) => {
      //     console.log();
      //   });
    </script>
  </body>
</html>
